name: maat_router_poc
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.3
  flutter: ^3.22.2

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.4.0
  flutter_hooks: ^0.20.4
  go_router: ^13.0.1
  provider: ^6.1.1
  sliver_tools: ^0.2.12

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  leancode_lint: ^13.0.0

flutter_gen:
  assets:
    enabled: false

flutter:
  uses-material-design: true
  generate: true